### PR TITLE
[Instrumentation.ConfluentKafka] Add named instrumentation support

### PR DESCRIPTION
**Pull request by g7ed6e**
## Changes

- Ensure options instances are hold by builder's instances.
- Add named instrumentation support (using Keyed service to ease integration in .NET Aspire)
- Add integration test variations

## Merge requirement checklist

* [x] [CONTRIBUTING](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/main/CONTRIBUTING.md) guidelines followed (license requirements, nullable enabled, static analysis, etc.)
* [x] Unit tests added/updated
* [x] Appropriate `CHANGELOG.md` files updated for non-trivial changes
* [ ] Changes in public API reviewed (if applicable)

### CODE REVIEW

**Comment by g7ed6e** [comment]
@eerhardt Can you please check that PR ?

**Review by eerhardt — APPROVED** [review]
Looks good to me

**Review by birojnayak — APPROVED** [review]
looks good to me

**Review by Kielek — COMMENTED** [review]
Public API reviewed + technical requirements to merge.

Other based on @birojnayak and @eerhardt. Merging.

**Review by Kielek — APPROVED** [review]

**Pull request merged**
