### PR TITLE
Enabled Nulls on Contrib.Shared And Related & Tests Projects

### PR DESCRIPTION
**Pull request by FernandoNunes**
## Changes
Enabled Nullability in Contrib.Shared and related projects where it has relations to. Also enabled on Test Projects

Manually enforced PublicAPI annotations for different architectures.

All tests are passing for all projects.

### CODE REVIEW

**Review by FernandoNunesWK — COMMENTED** [review]
Merged with latest and fixed conflicts.

**Review by FernandoNunesWK — COMMENTED** [review]
Merged with latest and fixed conflicts.

**Review by FernandoNunesWK — COMMENTED** [review]
Merged with latest and fixed conflicts.

**Comment by utpilla** [comment]
@FernandoNunes For ease of reviewing, please split this PR into smaller sized PRs targeting one component at a time. Refer to #969 for an example.

**Comment by FernandoNunes** [comment]
> 

Hi @utpilla, not sure how to do that or if its possible as when we change OpenTelemetry.Contrib.Shared we break all other dependencies. Can you please give further help on this ?

**Comment by Kielek** [comment]
> > 
> 
> Hi @utpilla, not sure how to do that or if its possible as when we change OpenTelemetry.Contrib.Shared we break all other dependencies. Can you please give further help on this ?

You can try `#nullable enable` per file
Example: https://github.com/open-telemetry/opentelemetry-dotnet/blob/735dd0d04c755af7cc1ddfe7565c53757f36d5ab/src/OpenTelemetry/Trace/Sampler.cs#L17

When all projects will be ready then you can remove it.

**Pull request closed without merging**
