### PR TITLE
[Extensions.AWS, ResourceDetectors.AWS] Release 1.3.0-beta.1

### PR DESCRIPTION
**Pull request by Kielek**
Towards #1268

## Changes

Prerequisite to release another AWS packages.
Please check changes in changelog for details.

The question is if it should be released as 1.3.0-beta.1 (as we changed the package name) or it has to be major release (2.0.0-beta.1) for Extension package.
My recommendation is to use the same version for ResourceDetectors as it was extracted from the old package.
@srprash, @Oberon00, @rypdal, please let me know what do you think about versioning.

Please provide a brief description of the changes here.

For significant contributions please make sure you have completed the following items:

* [x] Appropriate `CHANGELOG.md` updated for non-trivial changes
* ~~[ ] Design discussion issue #~~
* ~~[ ] Changes in public API reviewed~~

### CODE REVIEW

**Comment by rypdal** [comment]
We already released the OpenTelemetry.Instrumentation.AWSLambda with changed package name as [1.1.0-beta.2](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/Instrumentation.AWSLambda-1.1.0-beta.3/src/OpenTelemetry.Instrumentation.AWSLambda/CHANGELOG.md#110-beta2). I think we should stick with the same versioning for the other AWS packages.

**Comment by srprash** [comment]
I agree that we don't need a major version bump.

**Comment by srprash** [comment]
After the `Extensions.AWS` is released, we need to update the references of the old package name in rest of the packages.
https://github.com/search?q=repo%3Aopen-telemetry%2Fopentelemetry-dotnet-contrib%20OpenTelemetry.Contrib.Extensions.AWSXRay&type=code

But I think there could be an issue. Stable packages cannot have unstable dependencies. The build for the packages depending on `Extensions.AWS-1.3.0-beta.1` will likely start to fail.

**Comment by Kielek** [comment]
@srprash, if it is ok for your, I would go first with beta release. Then, when needed and confirmed that we do no make any mistake, we can make follow up release as stable package.

**Comment by srprash** [comment]
@Kielek That sounds good to me.

**Review by srprash — APPROVED** [review]

**Pull request merged**
