### PR TITLE
[ResourceDetectors.AWS] Implement support for some cloud.* attributes in AWS ECS detector

### PR DESCRIPTION
**Pull request by mmanciop**
## Changes

Implement support for the following resource attributes in the AWS ECS detector when using the metadata endpoint v4:

* cloud.account.id
* cloud.availability_zone
* cloud.region

Also, fix mispelling of the AWSSemanticConventions.AttributeCloudAvailableZone to AWSSemanticConventions.AttributeCloudAvailabilityZone

* [X] Appropriate `CHANGELOG.md` updated for non-trivial changes

### CODE REVIEW

**Comment by mmanciop** [comment]
The build error looks like something that is on `main`:

```
Run markdownlint .
src/OpenTelemetry.ResourceDetectors.Azure/README.md:44:231 MD056/table-column-count Table column count [Expected: 2; Actual: 3; Too many cells, extra data will be missing]
Error: Process completed with exit code 1.
```

**Comment by Kielek** [comment]
@ppittle, @normj, @birojnayak, please review

**Review by birojnayak — APPROVED** [review]
looks good to me.. thank you for adding additional details.

**Review by normj — APPROVED** [review]
Looks good

**Comment by Kielek** [comment]
@mmanciop, please update also README.md. There is a list of detected resource.

**Comment by mmanciop** [comment]
> @mmanciop, please update also README.md. There is a list of detected resource.

Done in 4ead9fd, and I retrofitted the update I forgot back when with #875. Although I gotta say, this format that does not neither mentions the actual keys, nor links to the specs of the semconvs, does not strike me as particularly useful.

**Comment by Kielek** [comment]
> > @mmanciop, please update also README.md. There is a list of detected resource.
> 
> Done in [4ead9fd](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/commit/4ead9fd7242e96625e9b50461f7451098a0d83d2), and I retrofitted the update I forgot back when with #875. Although I gotta say, this format that does not neither mentions the actual keys, nor links to the specs of the semconvs, does not strike me as particularly useful.

Other documentation relays on exact keys: https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/main/src/OpenTelemetry.ResourceDetectors.ProcessRuntime/README.md

It can be fixed as separate PR. Merging.

**Review by Kielek — APPROVED** [review]

**Pull request merged**
