### PR TITLE
WCF: Added TelemetryContractBehaviorAttribute to support programmatic configuration

### PR DESCRIPTION
**Pull request by CodeBlanch**

### CODE REVIEW

**Comment by CodeBlanch** [comment]
@mconnew If you have time would you mind reviewing this for me?

**Comment by mconnew** [comment]
@CodeBlanch, it looks like all you are intending is to create an attribute that can be applied to the ServiceContract instead of adding to the ChannelFactory or ServiceHost, if so, then this looks correct.

**Comment by CodeBlanch** [comment]
@mconnew

> It looks like all you are intending is to create an attribute that can be applied to the ServiceContract instead of adding to the ChannelFactory or ServiceHost, if so, then this looks correct.

That's what I was thinking, yes.

**Review by cijothomas — APPROVED** [review]

**Comment by CodeBlanch** [comment]
Now available in [OpenTelemetry.Contrib.Instrumentation.Wcf 1.0.0-rc3](https://www.nuget.org/packages/OpenTelemetry.Contrib.Instrumentation.Wcf/1.0.0-rc3)

**Pull request merged**
