### PR TITLE
[repo] Add dedicated CI for AspNet projects

### PR DESCRIPTION
**Pull request by CodeBlanch**
## Changes

* Adds dedicated CI for AspNet projects.
* Switches to a single tag for AspNet & AspNet.TelemetryHttpModule projects so that they will always be released together.
* Modifies `Component.Package.yml` to support multiple packages being released from the same tag.

## Details

Why switch to a single tag?

* If `AspNet.TelemetryHttpModule` is being changed, we always want to also push `AspNet`.

* If `AspNet` is being changed, we could run into trouble without also pushing `AspNet.TelemetryHttpModule`. For something like a pure bug fix, it would be fine to only push `AspNet`. However, `AspNet` gets its OTel API and DS references through the HttpModule project. It also directly depends on the exposed `AspNet.TelemetryHttpModule` APIs. If `AspNet.TelemetryHttpModule` was changed, for example do to an OTel API version bump, the `AspNet` package will be compiled against those bits but packaged targeting whatever the last tag was (older bits). Users consuming that package _could_ run into big issues. Pushing the two packages together makes it always safe without having to worry about what may be lurking in the repo.

### CODE REVIEW

**Review by Kielek — APPROVED** [review]
Previously, we have had technically two release on the GH side, now we will have only one with link to the AspNet project. Changelog for TelemetryModule will be not linked.

Ref: https://github.com/open-telemetry/opentelemetry-dotnet-contrib/releases/tag/Instrumentation.AspNet.TelemetryHttpModule-1.0.0-rc9.9 and https://github.com/open-telemetry/opentelemetry-dotnet-contrib/releases/tag/Instrumentation.AspNet-1.0.0-rc9.9

It will be great to have two of them in on GH release. I think it can be done in follow up PR.

**Comment by CodeBlanch** [comment]
Good call @Kielek! I'll look into it a bit.

**Comment by CodeBlanch** [comment]
@Kielek I just pushed support for including multiple packages in the GitHub release created by the package workflow.

**Review by Kielek — APPROVED** [review]

**Comment by CodeBlanch** [comment]
I realized there is one more issue with this. Here...

https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/37d430d23eaa6fdca49b67591810cfe346d7ea1f/.github/workflows/Component.Package.yml#L35-L36

...we only test the AspNet project. I need to switch it to test all projects (HttpModule too). To do that I have to tweak all the `.proj` files I have added for all the component-specific CIs to have a test target. Thinking I'm going to merge this and do that as a follow-up to keep the diff manageable.

**Pull request merged**
