### PR TITLE
Use Array.Empty<T>()

### PR DESCRIPTION
**Pull request by martincostello**
## Changes

Use `Array.Empty<string>()` instead of allocating a new array.

* [ ] Appropriate `CHANGELOG.md` updated for non-trivial changes
* [ ] Design discussion issue #

### CODE REVIEW

**Review by cijothomas — APPROVED** [review]

**Review by Kielek — APPROVED** [review]

**Review by Oberon00 — APPROVED** [review]

**Comment by Oberon00** [comment]
This looks like something that could & should be checked by a linter BTW. Any rules we could enable to catch this automatically?

**Comment by martincostello** [comment]
There's a built-in rule for this (I forget the number) in fairly recent versions of the .NET SDK (6+ at latest) that should detect such usage if enabled.

**Comment by Kielek** [comment]
I suppose that it can be detected if you enable `<AnalysisLevel>latest-All</AnalysisLevel>` in csproj. See: https://github.com/open-telemetry/opentelemetry-dotnet/issues/3958.

The warning: https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1825

**Comment by martincostello** [comment]
I'd be happy to do a PR to enable that separately - I think otherwise turning it on might find other unrelated diagnostics that need fixing and quickly make the scope of this otherwise small PR spiral.

**Comment by martincostello** [comment]
> I suppose that it can be detected if you enable `<AnalysisLevel>latest-All</AnalysisLevel>` in csproj. See for main repository: [open-telemetry/opentelemetry-dotnet#3958](https://github.com/open-telemetry/opentelemetry-dotnet/issues/3958).
> 
> The warning: https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1825

Have opened #908 to enable analysers.

**Pull request merged**
