### PR TITLE
[Instrumentation.AWS, Extensions.AWSXRay] Add net6.0 target, replace net452 target with net462

### LINKED ISSUE #1078: Consider removing `net452` target from the package
# Issue with OpenTelemetry.Contrib.Instrumentation.AWS
The package currently targets `net452` which is a non-supported version. Consider updating it to latest supported version i.e. `net462`.

## Additional Context
This issue is opened as part of #1031 effort

### PR DESCRIPTION
**Pull request by wjrogers**
Fixes #1078.

## Changes

Add a `net6.0` target to OpenTelemetry.Contrib.Instrumentation.AWS and OpenTelemetry.Contrib.Extensions.AWSXRay. Also, update the former's out-of-support `net452` target to `net462`, i.e. `NetFrameworkMinimumSupportedVersion`. I combined the updates to these two projects into one PR because the latter is a dependency of the former.

- Update conditional compilation symbols in tests project(s) from `NET452` to `NETFRAMEWORK`.
- Add a `net7.0` test target to Instrumentation.AWS.Tests to match Extensions.AWSXRay.Tests.
- Add a `netcoreapp3.1` test target to Extensions.AWSXRay to exercise the library's `netstandard2.0` target.
- In tests projects, suppress the build warning generated by System.Diagnostics.DiagnosticSource 7.0.0 when targeting out-of-support frameworks. (See open-telemetry/opentelemetry-dotnet#3448 for discussion.)
- Fix warnings from analyzers enabled by the new target. I tried to minimize the necessary code changes and add tests where I needed to make a non-trivial change.
- Remove now-unnecessary reference to System.Net.Http.

### CODE REVIEW

**Comment by vishweshbankwar** [comment]
@wjrogers We are working towards removing un-supported versions(https://github.com/open-telemetry/opentelemetry-dotnet-contrib/issues/1031) from the repo including unit test. `netcoreapp3.1` is out of support. Is there any specific reason you want to add `netcoreapp3.1`?

**Comment by wjrogers** [comment]
@vishweshbankwar I noticed that no tests were run for the `netstandard2.0` target and that Instrumentation.AWS.Tests already had a `netcoreapp3.1` test target, so I added the same target to `Extensions.AWSXRay.Tests` so that the tests would run against the `netstandard2.0` library assembly. There is some context in the [issue I linked](https://github.com/open-telemetry/opentelemetry-dotnet/issues/3448) about the difficulty of keeping `netstandard2.0` targets when every supported runtime will bind to a more-specific target (in this case, `net6.0`+ to `net6.0` and `net462`+ to `net462`). I am happy to remove it if you prefer, but that will mean the `netstandard2.0` build is untested.

Personally, given the fact there are no more supported runtimes that need it, I think it makes more sense to remove the `netstandard2.0` target from the library and provide only more-specific builds (`net6.0` and `net462`), but I didn't want to make that decision for you!

**Comment by wjrogers** [comment]
@cijothomas Sure. This PR is meant to combine with #1092 to remove a dependency when targeting `net6.0` or newer. My hope is to avoid taking a dependency on Newtonsoft.Json when I use this package in my own work. `net6.0` is the oldest supported runtime that includes System.Text.Json.

It's not strictly required to target `net6.0` — the reference to System.Text.Json would be enough — but I find it helpful when installing packages to see the minimal list of dependencies for each supported target framework. If that's not enough justification, I'd be happy to prepare a new PR that just bumps the minimum framework version for Instrumentation.AWS.

**Comment by cijothomas** [comment]
@wjrogers Thanks for the explanation. Could you update the PR description so its easy to why is this needed. And also I'd suggest to make the net452->net462 into a separate PR of its own.

**Comment by wjrogers** [comment]
> I'd suggest to make the net452->net462 into a separate PR of its own.

Have now done so as #1095. I will refresh this PR to isolate the `net6.0` addition later tonight or tomorrow. Thanks for the feedback!

**Comment by wjrogers** [comment]
I am closing this PR so I can push a new branch that affects only Extensions.AWSXRay, with a more interesting justification. I will follow up on Instrumentation.AWS if/when my other PRs are accepted.

**Comment by wjrogers** [comment]
continued in #1096

**Pull request closed without merging**
