### PR TITLE
Add Elastic APM Exporter

### PR DESCRIPTION
**Pull request by glucaci**
Add exporter implementation for Elastic APM (see https://www.elastic.co/guide/en/apm/server/current/events-api.html).
Initially opened in main repo https://github.com/open-telemetry/opentelemetry-dotnet/pull/2036.

- Span vs Transaction in Elastic. Current approach is that ActivityKind.Internal is a Span the rest are Transactions (see https://www.elastic.co/guide/en/apm/get-started/current/apm-data-model.html)

There are still two tasks which I will start when a the review on the main concepts is ok:
* [ ] HttpClient authorization
* [ ] `CHANGELOG.md` updated

### CODE REVIEW

**Comment by glucaci** [comment]
I think it make sense to have also a REST example as in the main repo. https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/examples/AspNetCore

**Comment by glucaci** [comment]
@cijothomas can I have a review on this one?
Thanks!

**Comment by cijothomas** [comment]
@ejsmith Would you have time to help review this? You are the only Elastic expert whom I know and has contributed before to this repo:)

**Comment by astorm** [comment]
@glucaci A colleague pointed me at this PR -- I don't think I can help with review (the closest I come to knowing .NET is 2001 era ASP pages) -- but this looks super neat! 

I do have a tangential question for you -- Elastic has both 

- [A Contrib. Exporter for the OpenTelemetry Collector](https://www.elastic.co/guide/en/apm/get-started/current/open-telemetry-elastic.html#open-telemetry-elastic-exporter)
- The ability for [APM Server to _act as_ an Open Telemetry collector](https://www.elastic.co/guide/en/apm/get-started/current/open-telemetry-elastic.html#open-telemetry-elastic-protocol)

Was there some missing feature that led you to develop an "in app/service" .NET exporter instead of using one of these solutions?  Or was this just something you saw that _could_ be in the world and decided to make it so?

**Comment by glucaci** [comment]
Thank for you response.

1. The contrib collector for elastic is an out-of-process collector which hast du run as a sidecar/daemonset etc, this implementation is an in-process solution.

2. Thanks for pointing it out, i will take a look on open-telemetry protocol APM Server ingestion and come back with a result.

**Comment by ejsmith** [comment]
@glucaci yeah, the APM server in Elasticsearch 7.13 natively supports the OLTP exporter now, but that still does require running the APM server. So this exporter might still be nice to go directly to Elasticsearch without needing a collector or APM service running somewhere.

**Comment by cyrille-leclerc** [comment]
Hello @glucaci . I'm on of @astorm's colleagues, I'm the product manager at Elastic in charge of the native support of OpenTelemetry and OTLP. Please tell us if there are gaps in our current support of OTLP, Elastic wants to provide best in class support for all OpenTelemetry SDKs, agents and collector, including of course .Net.

**Comment by glucaci** [comment]
Hi everyone,

Indeed, I've just tested the opentelemetry-dotnet ASP.NET Core instumentation with the OTPL exporter configured fot the APM Server and is working nice.

image

Therefor I will close this PR and start working on some instrumentation which we need like MongoDB, Azure BlobStorage, GraphQL etc.

@ejsmith why would you like to export to Elasticsearch only because you don't have any way of seeing traces without APM Server.

**Comment by ejsmith** [comment]
@glucaci you don't need the APM server to have APM support in Kibana.

**Comment by glucaci** [comment]
For sure you can do a lot of stuff in Kibana without needing an APM Server.

My intention was to support the APM Server integration with the opentelemetry-dotnet instrumentation. 
If you have another usecase and this PR did most part of it you can feel free to fork my branch [glucaci/elastic](https://github.com/glucaci/opentelemetry-dotnet-contrib/tree/elastic)

**Pull request closed without merging**
