### PR TITLE
Add EventId.Name support to Geneva exporter

### PR DESCRIPTION
**Pull request by maxgolov**
## Changes

Geneva Exporter presently supports exporting `EventId.Id` as `eventId`.

However, [EventId struct](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.logging.eventid?view=dotnet-plat-ext-7.0) **has two fields**:
- `Id` <- this one was exported.
- `Name` <- this one was not exported and simply ignored!?

Akin to `EventId.Id` being exported to `eventId`, the fix is to export the `EventId.Name` to `eventName`. Having the name on event enables much richer expressive definition of a `named event` using existing .NET API. It also enables full transparency into existing standard events, such as `Microsoft.Hosting.Lifetime` events. Instead of looking at cryptic Event IDs, devs can right away identify the meaning of event by using its name. It was a big mistake of not exporting it right away.

Examples of existing built-in ASP.NET event that uses named event, how it'd look like when sent to Geneva:
```
[
	{
		"TypeCode": 255,
		"Body": "0x2A13681400000000636EF762"
	},
	{
		"env_ver": "4.0",
		"env_name": "Log",
		"env_time": {
			"TypeCode": 255,
			"Body": "0x2A13681400000000636EF762"
		},
		"severityText": "Information",
		"severityNumber": 9,
		"name": "Microsoft.Hosting.Lifetime",
		"body": "Now listening on: {address}",
		"env_properties": {
			"address": "http://localhost:5252"
		},
		"eventId": 14,
		"eventName": "ListeningOnAddress"
	}
]
```

How to use it:
```
                logger.LogInformation(
                    new EventId(
                        12345,
                        "MyCustomEvent"),
                    "Hello {object}",
                    new { UserName = "maxgolov" }
                );
```

Subsequently devs can slice and dice their logs by `eventName` field. Our codebase heavily uses similar patterns and it is absolute necessity for us to implement support for the proper export of `EventId.Name` in order to fully onboard to OpenTelemetry.

### CODE REVIEW

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/309

**Comment by maxgolov** [comment]
@cijothomas @reyang - I see the older PR is blocked by Reiley Yang. When can we expect the fix to be merged?

I think there's been enough consensus building up, that explains the merit and the practical need for getting it in soon.

We need to get some traction on this, as this is practically the biggest blocker for us to fully embrace OpenTelemetry in our services.

cc: @craigktreasure

**Comment by Jaxelr** [comment]
I've been waiting for this PR (or similar versions) to be merge for some dashboards based on event information. So adding a bump here.

**Comment by maxgolov** [comment]
up

**Pull request closed without merging**
