### PR TITLE
[Sampler.Aws] perf improvements for AWS Xray sampler

### PR DESCRIPTION
**Pull request by birojnayak**
Fixes #
This fixes the issue mentioned here #2045 , the dotnet runtime issue is created [here] (https://github.com/dotnet/runtime/issues/107505)

## Changes

The changes are to write informational event to event source only when fallback sampler is called first time instead of calling repeatedly. **We saw an improvement in 4 times in TPS after this change** in our load testing.

Screenshot 2024-09-07 at 6 00 48 PM

## Merge requirement checklist

* [x ] [CONTRIBUTING](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/main/CONTRIBUTING.md) guidelines followed (license requirements, nullable enabled, static analysis, etc.)
* [ ] Unit tests added/updated
* [ ] Appropriate `CHANGELOG.md` files updated for non-trivial changes
* [x ] Changes in public API reviewed (if applicable)

### CODE REVIEW

**Review by ppittle — APPROVED** [review]

**Comment by Kielek** [comment]
I think that, the perf. improvements should be documented in the CHANGELOG.md.

**Review by vastin — APPROVED** [review]

**Comment by birojnayak** [comment]
Issue #2049 #2046 tagged.. #2049 is to release next alpha version

**Review by vastin — APPROVED** [review]
LGTM

**Review by Kielek — APPROVED** [review]
Approving, based on component owners needs.

**Pull request merged**
