### PR TITLE
Add Piotr as Approver

### PR DESCRIPTION
**Pull request by utpilla**
@Kielek has been actively contributing to this repo for a few months now. He is already an approver in the instrumentation repo (https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation) since Apr 2022 and has made significant contributions to the overall project in the past year.

Contributions include active reviews, efforts to standardize code style, diagnostics, project structure across all components for this repo, and expanding test coverage.

Link to all the PRs submitted by Piotr: https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pulls?q=is%3Apr+author%3Akielek

### CODE REVIEW

**Review by cijothomas — APPROVED** [review]

**Review by alanwest — APPROVED** [review]
Welcome, Piotr!

**Review by reyang — APPROVED** [review]
+1 (although my vote won't count)

**Review by CodeBlanch — APPROVED** [review]
Congrats @Kielek!

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/community/blob/main/community-membership.md#requirements-2 Proposed by maintainer, approved by all other maintainers. Merging.

Welcome @Kielek

**Pull request merged**
