### PR TITLE
[Instrumentation.Runtime] Release Runtime instrumentation version 1.0.0

### PR DESCRIPTION
**Pull request by xiang17**
Release Runtime instrumentation version 1.0.0.

## Changes

Update `CHANGELOG.md`.

For significant contributions please make sure you have completed the following items:

* [x] Appropriate `CHANGELOG.md` updated for non-trivial changes
* [x] Design discussion issue #335.

### CODE REVIEW

**Comment by pellared** [comment]
Should it not first land in the OTel specification [here](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/runtime-environment-metrics.md)?

**Comment by alanwest** [comment]
> Should it not first land in the OTel specification [here](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/runtime-environment-metrics.md)?

Related, are we banking on the assumption that the `process.runtime.` prefix to runtime metrics is stable? I mean I guess I would hope so 😆 as it was somewhat recent that this change was made https://github.com/open-telemetry/opentelemetry-specification/pull/2112/files

**Comment by xiang17** [comment]
> Should it not first land in the OTel specification [here](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/runtime-environment-metrics.md)?

I have been working with Reiley and also with folks from .NET runtime team including Tarek and Noah. It's a component blessed by .NET runtime owners (e.g. approvals from Noah in #475 and Maoni in #454 regarding .NET GC). And I don't intend to make any breaking changes.

**Comment by xiang17** [comment]
> > Should it not first land in the OTel specification [here](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/runtime-environment-metrics.md)?
> 
> Related, are we banking on the assumption that the `process.runtime.` prefix to runtime metrics is stable? I mean I guess I would hope so 😆 as it was somewhat recent that this change was made [open-telemetry/opentelemetry-specification#2112](https://github.com/open-telemetry/opentelemetry-specification/pull/2112)

I'm not sure what's the requirements for the spec to become stable. From what I heard it's gonna take very long to add/modify things in the spec, which would be a big delay if I set that as a prerequisite for this component.

**Review by noahfalk — APPROVED** [review]
LGTM!

**Comment by twenzel** [comment]
LGTM

**Review by twenzel — APPROVED** [review]

**Comment by xiang17** [comment]
Canceled/delayed this release because of a bug in an API on .NET 6: #495.

**Comment by xiang17** [comment]
This has been released in #553.

**Pull request closed without merging**
