### PR TITLE
[Instrumentation.AWS] Update AWS SDK references

### PR DESCRIPTION
**Pull request by normj**
## Changes
Update the AWS .NET SDK dependencies for the OpenTelemetry.Instrumentation.AWS package. This is needed because the version that was previously had a max range cap of `3.6` but the SDK has been on version `3.7` since 2021. Without this change users are getting restore warnings whenever they are using an SDK versions released in the last 2 years.

For background purposes I'm a developer of the AWS .NET SDK.

For significant contributions please make sure you have completed the following items:

* [ ] Appropriate `CHANGELOG.md` updated for non-trivial changes
* [ ] Design discussion issue #
* [ ] Changes in public API reviewed

### CODE REVIEW

**Comment by Kielek** [comment]
@normj, please add entry to the changelog.

**Comment by Oberon00** [comment]
>  had a max range cap of 3.6

Where does this max range cap come from? The reference here should be only a lower bound, see https://learn.microsoft.com/en-us/nuget/concepts/package-versioning#version-ranges

**Comment by normj** [comment]
> > had a max range cap of 3.6
> 
> Where does this max range cap come from? The reference here should be only a lower bound, see https://learn.microsoft.com/en-us/nuget/concepts/package-versioning#version-ranges
> 
> > ```
> > 
> > <PackageReference Include="ExamplePackage" Version="6.1" />
> > ```

The library is currently referencing version 3.5.0.26 of AWSSDK.SQS. If you look at the dependencies for that version it has a dependency on AWSSDK.Core set to `>= 3.5.1.24 && < 3.6.0`.  In more recent versions the service packages like AWSSDK.SQS have a much wider range set for the dependency on AWSSDK.Core. `>= 3.7.300 && < 4.0.0`.

https://www.nuget.org/packages/AWSSDK.SQS/3.5.0.26#dependencies-body-tab

**Comment by normj** [comment]
> @normj, please add entry to the changelog.

What should I set the release date to for the changeling?

**Review by Oberon00 — APPROVED** [review]

**Review by cijothomas — APPROVED** [review]

**Comment by normj** [comment]
@Kielek change log has been updated.

**Pull request merged**
