### PR TITLE
Fix null tags.

### LINKED ISSUE #565: Null attributes not handled properly
# Issue with OpenTelemetry.Exporter.Stackdriver

Stackdriver Beta1 (Open Telemetry Versions are not relevant)

**Is this a feature request or a bug?**

* [ ] Feature Request
* [x] Bug

I just the following exception:

```
Value cannot be null. (Parameter 'value') | System.ArgumentNullException
   at Google.Protobuf.ProtoPreconditions.CheckNotNullUnconstrained[T](T value, String name)
   at Google.Protobuf.Collections.MapField`2.set_Item(TKey key, TValue value)
   at Google.Protobuf.Collections.MapField`2.Add(TKey key, TValue value)
   at Google.Protobuf.Collections.MapField`2.Add(IDictionary`2 entries)
   at OpenTelemetry.Contrib.Exporter.Stackdriver.Implementation.ActivityExtensions.ToSpan(Activity activity, String projectId)
   at OpenTelemetry.Contrib.Exporter.Stackdriver.StackdriverTraceExporter.Export(Batch`1& batchActivity)
   at OpenTelemetry.BatchExportProcessor`1.ExporterProc()
   at System.Threading.Thread.StartCallback()
```

I think it is related to this line:

https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/main/src/OpenTelemetry.Exporter.Stackdriver/Implementation/ActivityExtensions.cs#L88

It makes totally sense, because AttributeMap is a GRPC structure, and GRPC does not accept null in general.

I reproduced it with the following example:

```
// See https://aka.ms/new-console-template for more information
using Google.Cloud.Trace.V2;
using OpenTelemetry.Exporter.Stackdriver;
using System.Diagnostics;

var toSpan = 
    typeof(StackdriverTraceExporter).Assembly
        .GetType("OpenTelemetry.Exporter.Stackdriver.Implementation.ActivityExtensions")!
        .GetMethod("ToSpan")!
        .CreateDelegate<Func<Activity, string, Span>>();

var activity = new Activity("Operation");
activity.AddTag("Key", null);
activity.Start();
activity.Stop();

var x = toSpan(activity, "PROJECT-ID");
```

### PR DESCRIPTION
**Pull request by SebastianStehle**
Fixes #565 

## Changes

* Convert null tags to correct attribute value.
* Fix tests, which were not using the correct activities.
* Fix an edge case where an invalid activity would throw exceptions in the exporter.

### CODE REVIEW

**Comment by SebastianStehle** [comment]
Please reopen

**Comment by utpilla** [comment]
Please resolve the merge conflicts.

**Comment by SebastianStehle** [comment]
Conflicts are solved.

**Review by Kielek — APPROVED** [review]

**Comment by utpilla** [comment]
Please fix the failing CI task as well.

**Comment by utpilla** [comment]
@SergeyKanzhelev Could you please review this PR?

**Comment by SebastianStehle** [comment]
I think it is a critical bug and it would be great if it can be merged asap

**Review by cijothomas — APPROVED** [review]

**Comment by utpilla** [comment]
@SebastianStehle Please add a CHANGELOG entry. After you have done that, if you would like a new version for the package released, please follow the steps mentioned here: https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/main/CONTRIBUTING.md#how-to-request-for-release-of-package

**Pull request merged**
