### PR TITLE
File scope namespaces for Geneva Exporter

### PR DESCRIPTION
**Pull request by mic-max**
Towards #276 

To get opinions and perform a smaller scale change before deciding to do this for other projects in the repo.

### CODE REVIEW

**Comment by cijothomas** [comment]
@mic-max its very hard to review big PRs. Please do it very small - like 2-5 classes at max.

**Review by reyang — APPROVED** [review]

**Comment by reyang** [comment]
> @mic-max its very hard to review big PRs. Please do it very small - like 2-5 classes at max.

This trick might help to make the review easier:

image

**Review by cijothomas — APPROVED** [review]

**Comment by mic-max** [comment]
> > @mic-max its very hard to review big PRs. Please do it very small - like 2-5 classes at max.
> 
> This trick might help to make the review easier:
> 
> image

What a Godsend that is for changes like this!

**Comment by cijothomas** [comment]
@mic-max please check the CI failures.

**Pull request merged**
