### PR TITLE
[Instrumentation.MassTransit] deprecate package + remove code

### PR DESCRIPTION
**Pull request by Kielek**
Replaces #779.

## Changes

Deprecate MassTransit.
Add information how to instrument MassTransit 8.0.0+.
Remove MassTransit code.

* [x] Appropriate `CHANGELOG.md` updated for non-trivial changes
* ~~[ ] Design discussion issue #~~

### CODE REVIEW

**Comment by Kielek** [comment]
@phatboyg, @alexvaluyskiy FYI

**Review by phatboyg — APPROVED** [review]
Yes, thank you!

**Review by reyang — APPROVED** [review]

**Comment by RagingKore** [comment]
Interesting, I would still leave an extension to simply add the source in a typed way.
Thoughts? @phatboyg

**Comment by phatboyg** [comment]
A typed way? It's literally `AddSource("MassTransit")` on the OTEL configuration. What would be typed about it?

**Review by cijothomas — APPROVED** [review]

**Pull request merged**
