### PR TITLE
Allow subtypes of default AWS service clients to be instrumented

### PR DESCRIPTION
**Pull request by jsteinich**
## Changes

Allow any type in `AmazonServiceClient` hierarchy to be instrumented rather than just direct subtypes.

### CODE REVIEW

**Comment by Kielek** [comment]
@jsteinich, please sign CLA before we can proceed with this PR.

**Comment by jsteinich** [comment]
> @jsteinich, please sign CLA before we can proceed with this PR.

I'm running into some issues getting it signed, but will keep attempting to get past them.

**Comment by jsteinich** [comment]
@Kielek CLA has been signed

**Review by Kielek — APPROVED** [review]

**Comment by Kielek** [comment]
@jsteinich, please fix dotnet format step

**Comment by Kielek** [comment]
@jsteinich, please merge main branch. I am not able to do this, as you are using organisation fork instead of your private for,

**Pull request merged**
