### PR TITLE
Assign correct value to ext_dt_spanId in Tld Geneva exporter

### PR DESCRIPTION
**Pull request by manio143**
## Changes

I was testing the Geneva TldExporter locally (it produces very nice info into the EventSource) and I noticed the spanId value was too long and the same as traceId, so I looked in the code and noticed it was assigning the wrong property to the field.

For significant contributions please make sure you have completed the following items:

* [x] Appropriate `CHANGELOG.md` updated for non-trivial changes
* [ ] Design discussion issue #
* [ ] Changes in public API reviewed

### CODE REVIEW

**Comment by Kielek** [comment]
@manio143, please sign CLA agreement by EasyCLA

**Comment by manio143** [comment]
> @manio143, please sign CLA agreement by EasyCLA

Done 👍

**Review by Havret — APPROVED** [review]
lgtm

**Review by utpilla — APPROVED** [review]

**Comment by manio143** [comment]
> LGTM with an entry in CHANGELOG.md.

Do you want me to make another change as part of this PR?

**Review by cijothomas — APPROVED** [review]
good catch!

**Comment by cijothomas** [comment]
> > LGTM with an entry in CHANGELOG.md.
> 
> Do you want me to make another change as part of this PR?

Yes please, to add changelog entry!

**Review by cijothomas — APPROVED** [review]

**Pull request merged**
