### PR TITLE
Downgrade `system.text.json` OpenTelemetry.ResourceDetectors.Azure

### PR DESCRIPTION
**Pull request by vishweshbankwar**
Fixes #.

## Changes

Please provide a brief description of the changes here.

For significant contributions please make sure you have completed the following items:

* [x] Appropriate `CHANGELOG.md` updated for non-trivial changes
* [ ] Design discussion issue #
* [ ] Changes in public API reviewed

### CODE REVIEW

**Review by rajkumar-rangaraj — APPROVED** [review]

**Review by TimothyMothra — APPROVED** [review]

**Review by Kielek — APPROVED** [review]

**Comment by Kielek** [comment]
Worth to add changelog entry and make a release shortly.

**Comment by vishweshbankwar** [comment]
> Worth to add changelog entry and make a release shortly.

Done

**Comment by Yun-Ting** [comment]
Just curious - why do we need this downgrade?

**Comment by Kielek** [comment]
@Yun-Ting, ref: https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/pull/2728#issuecomment-1651124449

In general, it reduces possibility to use in AutoInstrumentation.

**Comment by vishweshbankwar** [comment]
> Just curious - why do we need this downgrade?

Aligning with https://github.com/reyang/opentelemetry-dotnet/blob/6cfb898b917dd9bde14691fb92dbba3e5cba611c/Directory.Packages.props#L45. And having higher dependency brings challenges to auto-instrumentation when the user app already has reference to lower versions.

**Pull request merged**
