### PR TITLE
[Instrumentation.AWSLambda] Replace .NET 6 target with .NET 8 and add .NET Standard 2.0

### PR DESCRIPTION
**Pull request by joegoldman2**
## Changes

Replace .NET 6 target, which will be very soon out of support, with .NET 8 and add support for .NET Standard 2.0.

## Merge requirement checklist

* [x] [CONTRIBUTING](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/main/CONTRIBUTING.md) guidelines followed (license requirements, nullable enabled, static analysis, etc.)
* [ ] Unit tests added/updated
* [ ] Appropriate `CHANGELOG.md` files updated for non-trivial changes
* [ ] Changes in public API reviewed (if applicable)

### CODE REVIEW

**Comment by Oberon00** [comment]
I would prefer waiting at least for the "Block function create" date (Feb 28, 2025)
image

**Comment by joegoldman2** [comment]
> I would prefer waiting at least for the "Block function create" date (Feb 28, 2025) https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html

.NET 6 itself will be out of support before. People who still use .NET 6 will be able to keep the current package version, right?

**Comment by joegoldman2** [comment]
> I would prefer waiting at least for the "Block function create" date (Feb 28, 2025) https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html

The addition of .NET Standard 2.0 target should be fine for people who are targeting .NET 6 and less.

**Comment by Oberon00** [comment]
That looks fine to me. Do we even need .NET 8 separately if we have netstandard2.0 as target?

**Comment by joegoldman2** [comment]
> That looks fine to me. Do we even need .NET 8 separately if we have netstandard2.0 as target?

For all packages, I'm replacing .NET 6 with .NET 8 and add .NET Standard 2.0 if not already present. I think some features are not available if only .NET Standard is targeted (but not sure if it's the case for this package).

**Review by CodeBlanch — APPROVED** [review]
LGTM

**Pull request merged**
