### PR TITLE
Use OTEL 1.2.0

### PR DESCRIPTION
**Pull request by seanat280**
## Changes

Migrated all projects to OTEL 1.2.0.  As .Net 4.6.1 and lower are now past end of life, and OTEL has upped the lowest supported version of .Net, I migrated all projects to be at a minium of .Net4.6.2.  More details on the supported versions can be found here:
https://devblogs.microsoft.com/dotnet/net-framework-4-5-2-4-6-4-6-1-will-reach-end-of-support-on-april-26-2022/

### CODE REVIEW

**Comment by cijothomas** [comment]
@seanat280 Please avoid large PRs, and do this project by project.

**Comment by seanat280** [comment]
@cijothomas So just to be clear, I should tease this apart into 16 or so separate PRs?  I can do that when I get a minute.  Is there any other changes I would need to make for these changes to be mergeable?

**Comment by cijothomas** [comment]
> @cijothomas So just to be clear, I should tease this apart into 16 or so separate PRs? I can do that when I get a minute. Is there any other changes I would need to make for these changes to be mergeable?

No. Just do it one by one, so it is easy to spot any undesired effects/issues. 

Note: Unlike the main repo, each component this repo is expected to be independent of each other.

**Comment by cijothomas** [comment]
> > @cijothomas So just to be clear, I should tease this apart into 16 or so separate PRs? I can do that when I get a minute. Is there any other changes I would need to make for these changes to be mergeable?
> 
> No. Just do it one by one, so it is easy to spot any undesired effects/issues.
> 
> Note: Unlike the main repo, each component this repo is expected to be independent of each other.

May be not 16+ PRs. But any PR with max 10 files is reasonable as it is easy to review.

**Comment by benjiro** [comment]
@seanat280 Thanks for your initial work, I've split out MT, WCF, and EFCore projects into a smaller PR. https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/347

**Pull request closed without merging**
