### PR TITLE
Enable Nulls on Contrib.Extensions.AWSXRay & Test Projects

### PR DESCRIPTION
**Pull request by FernandoNunes**
Fixes #.

## Changes

Enabled Nulls (<Nullable>enable</Nullable>) on Contrib.Extensions.AWSXRay & Test Projects

### CODE REVIEW

**Comment by Kielek** [comment]
@FernandoNunes, please sign CLA, without this we want be able to merge your code.

I have approved run, but I expect a lot of issues related to the nullability part.

**Comment by FernandoNunes** [comment]
Hi @Kielek , I didn't noticed the project had warnings, my bad. I've commited the changes required for nullability checks and all tests are passing (netcoreapp3.1 & net452).

Also, I've signed the CLA.

**Comment by Kielek** [comment]
There are some compilation issues. Could you please address it?

**Comment by FernandoNunes** [comment]
> There are some compilation issues. Could you please address it?

Added missing #nullable enable
Sorry still getting the hang of it, I'll be more efficient next PRs.

**Comment by FernandoNunes** [comment]
Visual Studio suggests the fixes to PublicAPI but doesn't changes for all platform's PublicAPI.txts.
After all changes are applied to one, I've started reviewing them all by hand for all platforms.

**Comment by Kielek** [comment]
> Visual Studio suggests the fixes to PublicAPI but doesn't changes for all platform's PublicAPI.txts. After all changes are applied to one, I've started reviewing them all by hand for all platforms.

Unfortunately, it is the only way I know how to fix it.

**Review by srprash — APPROVED** [review]

**Comment by srprash** [comment]
@FernandoNunes The changes look good to me. Can you resolve the conflicts on this PR? Thanks!

**Comment by FernandoNunes** [comment]
> @FernandoNunes The changes look good to me. Can you resolve the conflicts on this PR? Thanks!

All checks have passed. After this one can you check other PRs I have open ? :)

**Review by utpilla — APPROVED** [review]

**Pull request merged**
