### PR TITLE
[geneva] Vendor code for writing tracepoints on Linux

### PR DESCRIPTION
**Pull request by CodeBlanch**
[Split off from #2113]

## Changes

* Adds code from https://github.com/microsoft/LinuxTracepoints-Net/ into the "External" folder in the GenevaExporter project. Decided to vendor this code because a) that package doesn't have a strong name which breaks the build and b) we're hoping dotnet/runtime will add support for [user_events](https://docs.kernel.org/trace/user_events.html) in the future and we won't need a dependency.

  Geneva will only be using the `PerfTracepoint` class. The files being included here are the subset from the repo required to get /Provider/PerfTracepoint.cs building.

## Merge requirement checklist

* [X] [CONTRIBUTING](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/main/CONTRIBUTING.md) guidelines followed (license requirements, nullable enabled, static analysis, etc.)

### CODE REVIEW

**Review by reyang — APPROVED** [review]

**Comment by rajkumar-rangaraj** [comment]
Could you please update the PR summary to show how you decided to select only part of these files from the other repo. Later if we need to copy an update it will be useful.

**Review by rajkumar-rangaraj — APPROVED** [review]
Also, consider adding information on why `#nullable enable` is added on every file.

**Comment by TimothyMothra** [comment]
For personal experience (we have to vendor code in the Azure Monitor Distro), you should add a changelog entry and link to the specific Tag or Commit Id that you copied from. 

In the future when you need to update this directory you can reference Tag2 in the changelog.

**Comment by CodeBlanch** [comment]
@rajkumar-rangaraj @TimothyMothra I pushed some changes geared towards reducing the amount of changes to the files which are being vendored. Goal being to make it easier to update them in the future if needed.

**Pull request merged**
