### PR TITLE
Add Guard exception throwing helper class

### PR DESCRIPTION
**Pull request by mic-max**
Towards https://github.com/open-telemetry/opentelemetry-dotnet-contrib/issues/283

Will make follow-up commits changing exception throws to use Guard class methods, if there is positive feedback on this PR to do so.

The guard class is taken from https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Api/Internal/Guard.cs as is. Not sure if the test should also be copied to this repository. There is likely a better way of sharing common helper code between open-source OTel .NET projects though... please share thoughts on this topic :)

### CODE REVIEW

**Review by reyang — APPROVED** [review]

**Review by cijothomas — APPROVED** [review]

**Comment by utpilla** [comment]
> Towards #307

#307 Towards #307 😂

**Comment by utpilla** [comment]
I feel we should be consistent with data validation. If we are using `Guard` we should use it consistently throughout all the projects of the solution. It's tough to enforce that and maintain that. Also, this would add more to the list of things to learn for future contributors.

My stand is that in the contrib repo we should go with the plain and obvious validation which all developers are aware of to keep things simple and easy.

**Comment by cijothomas** [comment]
> I feel we should be consistent with data validation. If we are using `Guard` we should use it consistently throughout all the projects of the solution. It's tough to enforce that and maintain that. Also, this would add more to the list of things to learn for future contributors.
> 
> My stand is that in the contrib repo we should go with the plain and obvious validation which all developers are aware of to keep things simple and easy.

Now that you made a case for this, I start to agree to this.. Waiting for any thoughts from other maintainers as well.

**Comment by CodeBlanch** [comment]
I feel like this would be good to have. The `Guard` extensions are a nice timesaver for those who want to use them. Fair criticism that everything in the repo might not use it, and that isn't ideal, but don't want to throw the baby out with the bathwater 😄

**Comment by cijothomas** [comment]
Merging this. We won't enforce all components to use this. Its nice-to-have :)

**Pull request merged**
