### PR TITLE
Add possibility to configure EntityFrameworkInstrumentationOptions via environment variables

### PR DESCRIPTION
**Pull request by bqk-**
## Changes

When using the default constructor for `EntityFrameworkInstrumentationOptions`, try to get SetDbStatementForText and SetDbStatementForStoredProcedure from environment variables.
This is useful when using Automatic Instrumentation, allowing you to have SQL query in traces without touching the instrumented application code.

- `OTEL_ENTITYFRAMEWORKCORE_SET_DB_STATEMENT_TEXT` -> SetDbStatementForText
- `OTEL_ENTITYFRAMEWORKCORE_SET_DB_STATEMENT_STORED_PROCEDURE` -> SetDbStatementForStoredProcedure

* [x] Appropriate `CHANGELOG.md` updated for non-trivial changes
* [ ] Design discussion issue #
* [ ] Changes in public API reviewed

### CODE REVIEW

**Comment by cijothomas** [comment]
https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/configuration/sdk-environment-variables.md#language-specific-environment-variables Must follow this guide if defining language specific environment variables.

**Comment by bqk-** [comment]
Fixed the naming.

The idea is to not touch the application code: https://opentelemetry.io/docs/instrumentation/net/automatic/
So by settings the proper environment variable where the application is deployed, you can configure the behaviour of the instrumented libraries.

**Comment by utpilla** [comment]
@bqk- Have you checked with the owners of the [auto instrumentation repo](https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation) for a workaround?

**Comment by bqk-** [comment]
@utpilla I implemented it here based on the comment found in that repo: https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/issues/2331#issuecomment-1498619659

**Pull request closed without merging**
