### PR TITLE
#229: NullReferenceException in TelemetryDispatchMessageInspector.BeforeSendReply when operation is OneWay

### PR DESCRIPTION
**Pull request by ievgen-platonov**
See details in the issue #229 (https://github.com/open-telemetry/opentelemetry-dotnet-contrib/issues/229)

### CODE REVIEW

**Comment by cijothomas** [comment]
> [CLA Not Signed](https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/9522512/261573555/237/#/?version=2)
> 
> * ❌ login: iepl  ([d931c47](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/commit/d931c4768a0089d2b01a1da4144ec049ace8e69a), [199c0aa](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/commit/199c0aac24d375ff01d84c8d903bd4e61d31c85b)). This user is authorized, but they must confirm their affiliation with their company. Start the authorization process [ by clicking here](https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/9522512/261573555/237/#/?version=2), click "Corporate",select the appropriate company from the list, then confirm your affiliation on the page that appears. For further assistance with EasyCLA, [please submit a support request ticket](https://jira.linuxfoundation.org/servicedesk/customer/portal/4).

@ievgen-platonov We need you to sign the CLA before we can accept any contributions. Please follow the instructions for the same.

**Comment by CodeBlanch** [comment]
@ievgen-platonov This looks good to me, thanks for the contribution! Would you mind updating the [CHANGELOG](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/blob/main/src/OpenTelemetry.Contrib.Instrumentation.Wcf/CHANGELOG.md)? You can add a section for "1.0.0-rc6" that's the version I'll use to release the fix.

**Comment by iepl** [comment]
@CodeBlanch Sure. Done.

**Comment by CodeBlanch** [comment]
@iepl Hey it looks like the markdownlint task failed on your CHANGELOG update. Needs a blank line like...

```
## 1.0.0-rc6

* Fixed a 'NullReferenceException' in
  'TelemetryDispatchMessageInspector.BeforeSendReply' when operation is OneWay
  ([#237](https://github.com/open-telemetry/opentelemetry-dotnet-contrib/pull/237))
```

I tried to fix it for you but it looks like I don't have access to your branch.

**Comment by iepl** [comment]
@CodeBlanch Fixed. I added some extra asserts as well. Just copied from existing test.

**Comment by iepl** [comment]
@CodeBlanch could you please tell when I can expect this changes in the package? We use wcf instrumentation in our product and will be great to understand when we can use new version with fix.

**Review by CodeBlanch — APPROVED** [review]
LGTM

**Pull request merged**
